apiVersion: batch/v1
kind: Job
metadata:
  name: simplevis-job
spec:
  template:
    spec:
      containers:
      - name: simplevis-job
        image: pn-50.davenet.local:8080/simplevis/simplevision:latest
      restartPolicy: Never
      volumeMounts:
      - mountPath: /dev/video0
        name: dev-video0
      securityContext:
        privileged: true
    volumes:
    - name: dev-video0
      hostPath:
        path: /dev/video0      
  backoffLimit: 4